# Generated by Django 3.2.3 on 2021-07-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medium', models.CharField(blank=True, choices=[('youtube', 'youtube'), ('soundcloud', 'soundcloud'), ('twitter', 'twitter'), ('instagram', 'instagram')], max_length=500, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('alias', models.CharField(max_length=50)),
                ('social_links', models.ManyToManyField(blank=True, to='artists.SocialLink')),
            ],
        ),
    ]
