# Generated by Django 3.2.3 on 2021-08-08 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='bio',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
    ]
